Bump _WIN32_WINNT to 0x0501, since that's what the compiler recommends to do when it complains about a value that is too low.
This complaint happens when building with 2010 -- I resolved these
complaints (here and in mysterx) by adding the definition to the vcxproj
files, but the 3m compilation still needs it.

For the record, the error text is:

  C:\Program Files\Microsoft Visual Studio 10.0\VC\ATLMFC\INCLUDE\atlcore.h(35) : fatal error C1189: #error :  This file requires _WIN32_WINNT to be #defined at least to 0x0403. Value 0x0501 or higher is recommended.